Addressed security issues found in vSphere provider gosec scan (LMSS-1190)
ranga-hpe/terraform-provider-vsphere pull request #1
Opened 2024-05-13 17:27 UTC by ajita-bhardwaj

### Description

Addressed security issues found in vSphere provider gosec scan
(https://jira-pro.it.hpe.com:8443/browse/LMSS-1190)

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/bhardaji/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/bhardaji/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Provider   Name | Rule ID | Issue details | location of   reported issue | Outcome | Reference
-- | -- | -- | -- | -- | --
VMWare   Vphere (https://github.com/ranga-hpe/terraform-provider-vsphere) | G401 (CWE-326) | Description:  Detect the usage of DES, RC4, MD5 or   SHA1 |   |   |  
  |   | Reported   warning message: Use of weak cryptographic primitive | Line no.44 in file vsphere/data_source_vsphere_host_thumbprint.go | tested   with SHA224 | https://pkg.go.dev/crypto/sha256
  | G402 (CWE-295) | Description:   Look for bad TLS connection settings |   |   |  
  |   | Reported   warning message: TLS MinVersion too low | 1.   Line no. in file vsphere/data_source_vsphere_host_thumbprint.go | tested   with MinVersion: tls.VersionTLS12 | https://github.com/redis/go-redis/issues/1553
  |   | Reported   warning message: TLS InsecureSkipVerify set true | 2.   Line no.383 in file vsphere/internal/helper/ovfdeploy/ovf_helper.go | self-signed   cert being used, will be handled outside of this PR |  
  | G505 (CWE-327) | Description:   Import blocklist: crypto/sha1 |   |   |  
  |   | Reported   warning message: weak cryptographic primitive | Line no.5 in file vsphere/data_source_vsphere_host_thumbprint.go | tested   with SHA224 | https://pkg.go.dev/crypto/sha256
  | G304 (CWE-22) | Description:   File path provided as taint input |   |   |  
  |   | Reported   warning message: Potential file inclusion via variable | 1.   Lines no.293, 268, 230 and 193 in file   vsphere/internal/helper/ovfdeploy/ovf_helper.go | tested   with var = filepath.Clean(var) | https://stackoverflow.com/questions/70281883/golang-untaint-url-variable-to-fix-gosec-warning-g107
  |   |   | 2.   Line no.324 in file   vsphere/internal/helper/contentlibrary/content_library_helper.go | tested   with var = filepath.Clean(var) | https://stackoverflow.com/questions/70281883/golang-untaint-url-variable-to-fix-gosec-warning-g107
  |   |   | 3.   Line no.527, 394 and 356 in file vsphere/config.go | tested   with var = filepath.Clean(var) | https://stackoverflow.com/questions/70281883/golang-untaint-url-variable-to-fix-gosec-warning-g107
  | G107 (CWE-88) | Description:   Url provided to HTTP request as taint input |   |   |  
  |   | Reported warning   message: Potential HTTP request made with variable url | Line no.354 in file vsphere/internal/helper/contentlibrary/content_library_helper.go | tested   with http.NewRequest | https://securego.io/docs/rules/g107.html
  | G601 (CWE-118) | Description: Implicit   memory aliasing of items from a range statement |   |   |  
  |   | Reported warning   message: Implicit memory aliasing in for loop. | Lines no.40, 68 and 102 in file vsphere/host_data_store_system_helper.go | tested   with var:=var in the for loop | https://stackoverflow.com/questions/62446118/implicit-memory-aliasing-in-for-loop

</body>

</html>

2024-05-14 09:57 UTC, ranga-hpe requested changes

2024-05-14 09:57 UTC, ranga-hpe commented on vsphere/host_data_store_system_helper.go
>  		if d.CanonicalName == name {
This change is still using the address of a variable that is in the loop scope, it is not clear that its memory will not be reused per iteration and freed after the loop is finished. Please use the indexing solution instead, for all reported instances of this pattern.
```
	for di, d := range disks {
		if d.CanonicalName == name {
			disk = &(disks[di])
			break
		}
	}
```

2024-05-14 12:56 UTC, ajita-bhardwaj commented on vsphere/host_data_store_system_helper.go
>  		if d.CanonicalName == name {
addressed

2024-05-16 11:29 UTC, RashmiMG approved these changes

2024-05-17 06:11 UTC, ranga-hpe approved these changes

2024-05-17 06:11 UTC, ranga-hpe commented on vsphere/host_data_store_system_helper.go
> -		if _, ok := o.Info.(*types.VmfsDatastoreAllExtentOption); ok {
The changes in lines 67 and 101 are not needed and may be wrong.

2024-05-17 06:11 UTC, merged